### ISSUE TITLE
Request version has security vulnerability

### ISSUE THREAD

**Issue by Lily418** [Daplie/le-acme-core#12]
Request 2.55.0 using a tough-cookie version with this vulnerability. 
https://nodesecurity.io/advisories/130

I would recommend updating request version to latest.

As an aside I wanted to make a PR to do this but the tests don't appear to have been maintained so I had no idea how to verify I didn't break anything with this change.

**Comment by coolaj86** [comment]
I'd kinda just like to drop request altogether and use the https module standalone... but I don't want to do the work for it.

Anyway, there's no special considerations for how request is used - just normal head, get, post so I just updated the deps.
