### ISSUE TITLE
Test doesn't run

### ISSUE THREAD

**Issue by gitgrimbo** [Daplie/le-acme-core#13]
`node test/test.js`

`Error: Cannot find module 'better-assert'`

[/test/test.js#L1](https://github.com/Daplie/le-acme-core/blob/9707b4dac8323c36ad9c26ebab1eb0514b0497d1/test/test.js#L1)

**Comment by gitgrimbo** [comment]
After installing `mocha` and `better-assert` I see 12/12 failures:

```
le-acme-core>mocha test\test.js


  config.json
    1) should contain required settings

  getCert
    2) should return cert, key and ca

  Certificate
    3) should be parsable
    4) should contain correct domain name
    5) should be valid at least 89 days

  Private key
    6) should be parsable

  Issuer certificate
    7) should be parsable
    8) should be valid

  PKCS#12
    9) should create .pfx file
    10) should be parsable

  challenge option
    11) should provide domain and challenge path and data

  Error handling
    12) should call callback with err


  0 passing (31ms)
  12 failing
```

**Comment by coolaj86** [comment]
To avoid confusion I've moved this issue over to the new repo and I'll be closing out this repo:

https://git.daplie.com/Daplie/le-acme-core/issues/18

I believe that we already merged in some changes related to tests https://git.daplie.com/Daplie/le-acme-core/merge_requests/4, but I think more work still needs to be done.

**Comment by coolaj86** [comment]
You can sign in with github at git.daplie.com to continue the discussion.
