### ISSUE TITLE
Check res before accessing body

### ISSUE THREAD

**Issue by manast** [Daplie/le-acme-core#16]
Here: https://github.com/Daplie/le-acme-core/blob/master/lib/register-new-account.js#L28
```body``` is accessed without checking if ```res``` actually is defined which in some situations leads to this error:
```
/proxy/node_modules/le-acme-core/lib/register-new-account.js:28
        return handleErr(err, 'Registration request failed: ' + res.body.toString('utf8'));
                                                                   ^

TypeError: Cannot read property 'body' of undefined
    at getTerms (/proxy/node_modules/le-acme-core/lib/register-new-account.js:28:68)

```

**Comment by coolaj86** [comment]
Opened as https://git.daplie.com/Daplie/le-acme-core/issues/16 and scheduled for fix and release tomorrow (feel free to fix and PR).

**Comment by DrewWarrenTIY** [comment]
@manast Thank you for finding this bug and creating the issue. The current version of le-acme-core is v2.0.8
